version: "3.7"

services:
  proxy:
    image: nginx:1.15.9-alpine
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.proxy"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - api_net
      - monitor
    depends_on:
      - the-book-pundit

  the-book-pundit:
    working_dir: /opt/app
    image: bahtou/the-book-pundit:latest
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.thebookpundit"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - NODE_PORT=3000
      - APP_SERVICE=the-book-pundit
      - GOODREADS_API_SERVICE=api.thebookpundit.app
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=pundit
      - POSTGRES_PASSWORD=iheartbooks
      - POSTGRES_DB=thebookpundit
      - POSTGRES_POOLSIZE=10
      - POSTGRES_IDLETIMEOUTMILLIS=20000
      - POSTGRES_RETRY_MAX_TIME=900000
      - POSTGRES_RETRY_CONNECTION=5000
    networks:
      - api_net
      - db_net
      - monitor
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 2
        delay: 3s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      placement:
        constraints: [node.role == manager]
    depends_on:
      - postgres
      - elasticsearch
      - fluentbit

  postgres:
    image: postgres:11.2-alpine
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.database"
    environment:
      - POSTGRES_USER=pundit
      - POSTGRES_PASSWORD=iheartbooks
      - POSTGRES_DB=thebookpundit
    ports:
      - 5432:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - type: volume
        source: pgData
        target: /var/lib/postgresql/data
    networks:
      - db_net
      - monitor
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      placement:
        constraints: [node.role == manager]

  elasticsearch:
    container_name: log-database
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    environment:
      - xpack.security.enabled=false
    deploy:
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 900M
      placement:
        constraints: [node.role == manager]
    volumes:
      - elData:/usr/share/elasticsearch/data
    networks:
      - monitor

  kibana:
    container_name: log-dashboard
    image: docker.elastic.co/kibana/kibana:6.6.2
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      resources:
        reservations:
          memory: 600M
        limits:
          memory: 900M
      placement:
        constraints: [node.role == worker]
    ports:
      - 5601:5601
    networks:
      - monitor
    depends_on:
      - elasticsearch

  fluentbit:
    labels:
      container.description: "fluentbit container discription"
    container_name: log-collector
    image: fluent/fluent-bit:1.0.4
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    deploy:
      endpoint_mode: vip
      labels:
        service.description: "fluentbit service description"
      mode: global
    ports:
      - 24224:24224
    volumes:
      - ./docker_to_es.conf:/fluent-bit/etc/fluent-bit.conf
    networks:
      - monitor
    depends_on:
      - elasticsearch

networks:
  api_net:
  db_net:
  monitor:

volumes:
  pgData:
  elData:
