version: "3.7"

services:
  proxy:
    image: bahtou/nginx-debug
    container_name: proxy
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: docker.proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - api_net
      - monitor
    depends_on:
      - the-book-pundit

  the-book-pundit:
    working_dir: /opt/app
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: docker.app
    image: the-book-pundit
    container_name: the-book-pundit
    build:
      context: .
      dockerfile: Dockerfile
    command: ./node_modules/.bin/nodemon --inspect=0.0.0.0:9229 ./bin/www
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - NODE_ENV=local
      - NODE_PORT=3000
      - APP_SERVICE=the-book-pundit
      - GOODREADS_API_SERVICE=http://0.0.0.0:3001
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=pundit
      - POSTGRES_PASSWORD=iheartbooks
      - POSTGRES_DB=thebookpundit
      - POSTGRES_POOLSIZE=10
      - POSTGRES_IDLETIMEOUTMILLIS=20000
      - POSTGRES_RETRY_MAX_TIME=900000
      - POSTGRES_RETRY_CONNECTION=5000
    volumes:
      - ./package.json:/opt/app/package.json
      - ./package-lock.json:/opt/app/package-lock.json
      - type: bind
        source: ./bin
        target: /opt/app/bin
        consistency: "delegated" # Docker Desktop for Mac: The container runtime’s view of the mount is authoritative. There may be delays before updates made in a container are visible on the host
        volume:
          nocopy: true
      - type: bind
        source: ./src
        target: /opt/app/src
        consistency: "delegated" # Docker Desktop for Mac: The container runtime’s view of the mount is authoritative. There may be delays before updates made in a container are visible on the host
        volume:
          nocopy: true
      - type: volume
        source: notused
        target: /opt/app/node_modules
    networks:
      - api_net
      - db_net
      - monitor
    depends_on:
      - postgres
      - elasticsearch
      - fluentbit

  postgres:
    image: postgres:11.2-alpine
    container_name: storage
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: docker.storage
    environment:
      - POSTGRES_USER=pundit
      - POSTGRES_PASSWORD=iheartbooks
      - POSTGRES_DB=thebookpundit
    ports:
      - 5432:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - type: volume
        source: pgData
        target: /var/lib/postgresql/data
    networks:
      - db_net
      - monitor
    depends_on:
      - fluentbit

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: log-database
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    deploy:
      resources:
        reservations:
          memory: 500M
      placement:
        constraints: [node.role == manager]
    volumes:
      - elData:/usr/share/elasticsearch/data
    networks:
      - monitor

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    container_name: log-dashboard
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      resources:
        reservations:
          memory: 600M
        limits:
          memory: 900M
      placement:
        constraints: [node.role == worker]
    ports:
      - 5601:5601
    networks:
      - monitor
    depends_on:
      - elasticsearch

  fluentbit:
    labels:
      container.description: "fluentbit container discription"
    image: bahtou/fluentbit-debug
    deploy:
      endpoint_mode: vip
      labels:
        service.description: "fluentbit service description"
    ports:
      - 24224:24224
    networks:
      - monitor
    depends_on:
      - elasticsearch

networks:
  api_net:
  db_net:
  monitor:
    attachable: true

volumes:
  pgData:
  elData:
  notused:
